(()=>{
const BUILTIN_IPA={"amplify":"/ˈæmplɪfaɪ/","breach":"/briːtʃ/","cascade":"/kæˈskeɪd/","centralized":"/ˈsentrəlaɪzd/","concentration":"/ˌkɑːnsənˈtreɪʃən/","contagion":"/kənˈteɪdʒən/","compromise":"/ˈkɑːmprəmaɪz/","confidential":"/ˌkɑːnfɪˈdenʃəl/","disruption":"/dɪsˈrʌpʃən/","emergency":"/ɪnˈmɜːrdʒənsi/","fraud":"/frɔːd/","governance":"/ˈɡʌvərnəns/","hazard":"/ˈhæzərd/","inherent":"/ɪnˈhɪrənt/","interconnected":"/ˌɪntərkəˈnektɪd/","interrupt":"/ˌɪntəˈrʌpt/","malicious":"/məˈlɪʃəs/","mutual":"/ˈmjuːtʃuəl/","oversight":"/ˈoʊvərsaɪt/","protocol":"/ˈproʊtəkɔːl/","redundancy":"/rɪˈdʌndənsi/","safeguard":"/ˈseɪfɡɑːrd/","supervise":"/ˈsuːpərvaɪz/","systemic":"/sɪˈstemɪk/","transaction":"/trænˈzækʃən/","unauthorized":"/ʌnˈɔːθəraɪzd/","vulnerability":"/ˌvʌlnərəˈbɪləti/","withstand":"/wɪðˈstænd/","anomaly":"/əˈnɑːməli/","assurance":"/əˈʃʊrəns/","associate":"/əˈsoʊʃieɪt/","consecutive":"/kənˈsekjətɪv/","crisis":"/ˈkraɪsɪs/","decisive":"/dɪˈsaɪsɪv/","deficiency":"/dɪˈfɪʃənsi/","destabilize":"/diːˈsteɪbəlaɪz/","forensic":"/fəˈrenzɪk/","insurer":"/ɪnˈʃʊrər/","intermediary":"/ˌɪntərˈmiːdieri/","jurisdiction":"/ˌdʒʊrɪsˈdɪkʃən/","recovery":"/rɪˈkʌvəri/","reputation":"/ˌrepjəˈteɪʃən/","robust":"/roʊˈbʌst/","simultaneous":"/ˌsaɪməlˈteɪniəs/","suspend":"/səˈspend/","threat":"/θret/","trace":"/treɪs/","ultimate":"/ˈʌltɪmət/","violate":"/ˈvaɪəleɪt/","vigilance":"/ˈvɪdʒələns/","accountable":"/əˈkaʊntəbəl/","consensus":"/kənˈsensəs/","obligation":"/ˌɑːbləˈɡeɪʃən/","authority":"/əˈθɔːrəti/","confirm":"/kənˈfɜːrm/","agency":"/ˈeɪdʒənsi/","crucial":"/ˈkruːʃəl/","legitimate":"/lɪˈdʒɪtəmət/","verify":"/ˈverɪfaɪ/","resilience":"/rɪˈzɪliəns/","liquidity":"/lɪˈkwɪdəti/","uncertainty":"/ʌnˈsɜːrtənti/"};
const ipa={...BUILTIN_IPA,...(window.KAOYAN_IPA||{})};
const maps=[['new',window.KAOYAN_NEW||{}],['review',window.KAOYAN_REVIEW||{}]];
const audioMap=Object.fromEntries(Object.entries(window.KAOYAN_AUDIO||{}).map(([k,v])=>[k.toLowerCase(),v]));
const wordTypeMap={};maps.forEach(([type,map])=>Object.keys(map).forEach(w=>wordTypeMap[w.toLowerCase()]=type));
const dayKey=(location.pathname.match(/(\d{4}-\d{2}-\d{2})\.html$/)||[])[1]||null;
const PROGRESS_KEY='kaoyan_progress_v1';
let progressStore={version:1,days:{}};
try{const raw=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null');if(raw&&typeof raw==='object')progressStore={version:1,...raw,days:raw.days||{}};}catch(e){}
function nowISO(){return new Date().toISOString();}
function getDayProgress(create=true){if(!dayKey)return null;if(!progressStore.days[dayKey]&&create)progressStore.days[dayKey]={visits:0,firstVisit:nowISO(),lastVisit:null,words:{},translations:{},totalNew:0,totalReview:0};const d=progressStore.days[dayKey];if(d){d.words=d.words||{};d.translations=d.translations||{};}return d||null;}
function saveProgress(){try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(progressStore));}catch(e){}}
const dayProgress=getDayProgress();
if(dayProgress){dayProgress.totalNew=Object.keys(window.KAOYAN_NEW||{}).length||dayProgress.totalNew||0;dayProgress.totalReview=Object.keys(window.KAOYAN_REVIEW||{}).length||dayProgress.totalReview||0;dayProgress.visits=(dayProgress.visits||0)+1;dayProgress.lastVisit=nowISO();saveProgress();}
function recordWordAction(word,action,type){const d=getDayProgress();if(!d)return;const key=word.toLowerCase(),now=nowISO();const w=d.words[key]||(d.words[key]={type:type||wordTypeMap[key]||'unknown',meaningClicks:0,audioClicks:0,firstMeaningAt:null,lastMeaningAt:null,firstAudioAt:null,lastAudioAt:null});if(type)w.type=type;if(action==='meaning'){w.meaningClicks=(w.meaningClicks||0)+1;if(!w.firstMeaningAt)w.firstMeaningAt=now;w.lastMeaningAt=now;}else if(action==='audio'){w.audioClicks=(w.audioClicks||0)+1;if(!w.firstAudioAt)w.firstAudioAt=now;w.lastAudioAt=now;}saveProgress();updateProgressSummary();}
function recordTranslation(index){const d=getDayProgress();if(!d)return;const key=String(index),now=nowISO();const t=d.translations[key]||(d.translations[key]={opens:0,firstOpenedAt:null,lastOpenedAt:null});t.opens=(t.opens||0)+1;if(!t.firstOpenedAt)t.firstOpenedAt=now;t.lastOpenedAt=now;saveProgress();updateProgressSummary();}
function dayMetrics(d){const words=Object.values(d?.words||{});const viewedNew=words.filter(w=>w.type==='new'&&(w.meaningClicks||0)>0).length;const viewedReview=words.filter(w=>w.type==='review'&&(w.meaningClicks||0)>0).length;const meaningClicks=words.reduce((s,w)=>s+(w.meaningClicks||0),0);const audioClicks=words.reduce((s,w)=>s+(w.audioClicks||0),0);const translationOpens=Object.values(d?.translations||{}).reduce((s,t)=>s+(t.opens||0),0);const active=meaningClicks+audioClicks+translationOpens>0;return {viewedNew,viewedReview,meaningClicks,audioClicks,translationOpens,active};}
function updateProgressSummary(){const el=document.getElementById('learningStats'),d=getDayProgress(false);if(!el||!d)return;const x=dayMetrics(d);el.textContent=`学习记录：词义点击 ${x.meaningClicks} 次 · 发音 ${x.audioClicks} 次 · 翻译 ${x.translationOpens} 次 · 本页访问 ${d.visits||1} 次`;}
let activeUtterance=null,activeAudio=null;
function stopAudio(){try{if(activeAudio){activeAudio.pause();activeAudio.currentTime=0;activeAudio=null;}}catch(e){}}
function tts(word){if(!('speechSynthesis' in window))return false;try{stopAudio();const synth=window.speechSynthesis;synth.cancel();const u=new SpeechSynthesisUtterance(word);activeUtterance=u;u.lang='en-US';u.rate=.82;u.pitch=1;u.volume=1;const voices=synth.getVoices();const v=voices.find(x=>/^en-US/i.test(x.lang))||voices.find(x=>/^en/i.test(x.lang));if(v)u.voice=v;u.onend=u.onerror=()=>{if(activeUtterance===u)activeUtterance=null;};synth.speak(u);return true;}catch(e){return false;}}
function speak(word){const key=word.toLowerCase(),src=audioMap[key];if(!src)return tts(key);try{window.speechSynthesis?.cancel();stopAudio();const a=new Audio(src);activeAudio=a;a.preload='auto';const fallback=()=>{if(activeAudio===a)activeAudio=null;try{a.pause();}catch(e){}tts(key);};a.onerror=fallback;a.onended=()=>{if(activeAudio===a)activeAudio=null;};const p=a.play();if(p&&typeof p.catch==='function')p.catch(fallback);return true;}catch(e){return tts(key);}}
function makePhonetic(word,label=word){const ph=document.createElement('button');ph.type='button';ph.className='phonetic';ph.dataset.speak=word;ph.setAttribute('aria-label',`播放 ${label} 的发音`);ph.title=audioMap[word.toLowerCase()]?'真人美式发音；播放失败时自动使用 Chrome 美式发音':'暂无预缓存真人音频，使用 Chrome 美式发音';ph.textContent=(ipa[word]||'')+' 🔊';ph.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();recordWordAction(word,'audio',wordTypeMap[word.toLowerCase()]);speak(word);},{passive:false});return ph;}
function injectTranslations(article,translations){if(!article||!Array.isArray(translations))return;[...article.querySelectorAll(':scope > p')].forEach((p,i)=>{if(p.nextElementSibling?.classList.contains('translation-wrap'))return;const zh=translations[i];if(!zh)return;const box=document.createElement('div');box.className='translation-wrap';const btn=document.createElement('button');btn.type='button';btn.className='translation-toggle';btn.textContent='查看中文翻译';btn.setAttribute('aria-expanded','false');const panel=document.createElement('div');panel.className='translation-panel';panel.hidden=true;panel.textContent=zh;btn.addEventListener('click',()=>{const open=panel.hidden;panel.hidden=!open;btn.textContent=open?'收起中文翻译':'查看中文翻译';btn.setAttribute('aria-expanded',String(open));if(open)recordTranslation(i);});box.append(btn,panel);p.after(box);});}
async function loadTranslations(article){const inline=Array.isArray(window.KAOYAN_TRANSLATIONS)?window.KAOYAN_TRANSLATIONS:[];if(inline.length){injectTranslations(article,inline);return;}const m=location.pathname.match(/(\d{4}-\d{2}-\d{2})\.html$/);if(!m)return;try{const r=await fetch(`../data/translations/${m[1]}.json`,{cache:'no-store'});if(r.ok)injectTranslations(article,await r.json());}catch(e){}}
const article=document.querySelector('.article');
if(article){const all={};maps.forEach(([type,map])=>Object.entries(map).forEach(([w,zh])=>all[w.toLowerCase()]={type,zh}));const keys=Object.keys(all).sort((a,b)=>b.length-a.length);if(keys.length){const esc=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),re=new RegExp('\\b('+keys.map(esc).join('|')+')\\b','gi');const walker=document.createTreeWalker(article,NodeFilter.SHOW_TEXT),nodes=[];while(walker.nextNode())if(!walker.currentNode.parentElement.closest('button,script,style'))nodes.push(walker.currentNode);nodes.forEach(node=>{const text=node.nodeValue;if(!re.test(text)){re.lastIndex=0;return;}re.lastIndex=0;const frag=document.createDocumentFragment();let last=0;text.replace(re,(match,_,offset)=>{frag.append(text.slice(last,offset));const key=match.toLowerCase(),d=all[key];const b=document.createElement('button');b.className='word'+(d.type==='review'?' review':'');b.dataset.word=key;b.dataset.type=d.type;b.append(document.createTextNode(match));const s=document.createElement('span');s.textContent=`（${d.zh}）`;b.append(s);frag.append(b);frag.append(makePhonetic(key,match));last=offset+match.length;return match;});frag.append(text.slice(last));node.replaceWith(frag);});}loadTranslations(article);}
function enhanceVocabList(details,map){if(!details||!map||!Object.keys(map).length)return;const old=details.querySelector('p');if(!old)return;const wrap=document.createElement('div');wrap.className='vocab-list';Object.entries(map).forEach(([word,zh])=>{const key=word.toLowerCase();const row=document.createElement('div');row.className='vocab-item';const head=document.createElement('span');head.className='vocab-head';const w=document.createElement('b');w.textContent=word;head.append(w,document.createTextNode(' '),makePhonetic(key,word));const meaning=document.createElement('span');meaning.className='vocab-meaning';meaning.textContent=' '+zh;row.append(head,meaning);wrap.append(row);});old.replaceWith(wrap);}
const detailEls=[...document.querySelectorAll('details')];enhanceVocabList(detailEls.find(d=>/今日\s*50\s*个新词|今日新词/.test(d.querySelector('summary')?.textContent||'')),window.KAOYAN_NEW||{});enhanceVocabList(detailEls.find(d=>/今日复习词/.test(d.querySelector('summary')?.textContent||'')),window.KAOYAN_REVIEW||{});
let masteredSet=new Set();try{masteredSet=new Set(JSON.parse(localStorage.getItem('kaoyan_mastered')||'[]'));}catch(e){}
const viewedNew=new Set(),viewedReview=new Set();if(dayProgress)Object.entries(dayProgress.words||{}).forEach(([word,w])=>{if((w.meaningClicks||0)>0){if(w.type==='new')viewedNew.add(word);if(w.type==='review')viewedReview.add(word);}});const totalNew=Object.keys(window.KAOYAN_NEW||{}).length,totalReview=Object.keys(window.KAOYAN_REVIEW||{}).length;
function updateCounters(){const n=document.getElementById('newCount'),r=document.getElementById('reviewCount');if(n)n.textContent=`新词已查看 ${viewedNew.size}/${totalNew}`;if(r)r.textContent=`复习词已查看 ${viewedReview.size}/${totalReview}`;}
document.querySelectorAll('.word').forEach(e=>{if(masteredSet.has(e.dataset.word))e.classList.add('mastered');e.onclick=()=>{e.classList.toggle('open');if(e.classList.contains('open')){if(e.dataset.type==='new')viewedNew.add(e.dataset.word);if(e.dataset.type==='review')viewedReview.add(e.dataset.word);recordWordAction(e.dataset.word,'meaning',e.dataset.type);updateCounters();}};e.oncontextmenu=x=>{x.preventDefault();const w=e.dataset.word;masteredSet.has(w)?masteredSet.delete(w):masteredSet.add(w);document.querySelectorAll('.word').forEach(q=>{if(q.dataset.word===w)q.classList.toggle('mastered',masteredSet.has(w));});localStorage.setItem('kaoyan_mastered',JSON.stringify([...masteredSet]));renderDashboard();};});updateCounters();
const info=document.getElementById('newCount')?.closest('.card');if(info&&!document.getElementById('learningStats')){const stats=document.createElement('p');stats.id='learningStats';stats.className='muted';stats.style.marginBottom='0';info.append(stats);updateProgressSummary();}
if(info&&!document.getElementById('chromeTtsTest')){const btn=document.createElement('button');btn.type='button';btn.id='chromeTtsTest';btn.className='btn';btn.textContent='🔊 测试 Chrome 发音';btn.title='强制使用浏览器 Web Speech API，不使用预缓存真人音频';const status=document.createElement('span');status.id='chromeTtsStatus';status.className='muted';status.style.marginLeft='8px';btn.addEventListener('click',()=>{if(tts('systemic')){status.textContent='正在用浏览器语音朗读：systemic';setTimeout(()=>{status.textContent='';},3500);}else status.textContent='当前浏览器不支持 speechSynthesis';});info.append(document.createElement('br'),btn,status);}
if('speechSynthesis' in window){window.speechSynthesis.getVoices();window.speechSynthesis.addEventListener?.('voiceschanged',()=>window.speechSynthesis.getVoices(),{once:true});}
function localDateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;}
function addDays(key,delta){const d=new Date(key+'T12:00:00');d.setDate(d.getDate()+delta);return localDateKey(d);}
function allWordStats(){const out={};Object.entries(progressStore.days||{}).forEach(([date,d])=>Object.entries(d.words||{}).forEach(([word,w])=>{const x=out[word]||(out[word]={word,meaningClicks:0,audioClicks:0,days:0,lastAt:null,reviewSeen:0,newSeen:0});x.meaningClicks+=w.meaningClicks||0;x.audioClicks+=w.audioClicks||0;x.days++;if(w.type==='review')x.reviewSeen++;if(w.type==='new')x.newSeen++;const t=w.lastMeaningAt||w.lastAudioAt||null;if(t&&(!x.lastAt||t>x.lastAt))x.lastAt=t;}));return out;}
function streakCount(){const active=new Set(Object.entries(progressStore.days||{}).filter(([,d])=>dayMetrics(d).active).map(([k])=>k));let k=localDateKey(),count=0;if(!active.has(k))k=addDays(k,-1);while(active.has(k)){count++;k=addDays(k,-1);}return count;}
function recentActivity(days=7){const arr=[];for(let i=days-1;i>=0;i--){const key=addDays(localDateKey(),-i),d=progressStore.days[key],m=dayMetrics(d);arr.push({key,active:m.active,viewed:m.viewedNew+m.viewedReview,clicks:m.meaningClicks+m.audioClicks+m.translationOpens});}return arr;}
function setText(id,text){const e=document.getElementById(id);if(e)e.textContent=text;}
function renderDashboard(){const dash=document.getElementById('progressDashboard');if(!dash)return;try{const raw=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null');if(raw?.days)progressStore={version:1,...raw,days:raw.days};}catch(e){}try{masteredSet=new Set(JSON.parse(localStorage.getItem('kaoyan_mastered')||'[]'));}catch(e){}const today=localDateKey(),td=progressStore.days[today],tm=dayMetrics(td),todayTotal=td?.totalNew||50;setText('dashToday',`${tm.viewedNew}/${todayTotal}`);const bar=document.getElementById('dashTodayBar');if(bar)bar.style.width=`${todayTotal?Math.min(100,Math.round(tm.viewedNew/todayTotal*100)):0}%`;setText('dashStreak',`${streakCount()} 天`);const stats=allWordStats(),unique=Object.keys(stats).length;setText('dashWords',`${unique}`);setText('dashMastered',`${masteredSet.size}`);const recent=recentActivity(7),activeDays=recent.filter(x=>x.active).length;setText('dash7',`${activeDays}/7 天`);const activity=document.getElementById('activity7');if(activity){activity.innerHTML='';recent.forEach(x=>{const cell=document.createElement('div');cell.className='activity-day'+(x.active?' active':'');cell.title=`${x.key}：${x.clicks} 次学习操作`;cell.innerHTML=`<span>${x.key.slice(5)}</span><b>${x.viewed}</b>`;activity.append(cell);});}const weak=Object.values(stats).filter(x=>!masteredSet.has(x.word)&&x.meaningClicks>0).sort((a,b)=>(b.meaningClicks+b.reviewSeen*2)-(a.meaningClicks+a.reviewSeen*2)).slice(0,8);const weakBox=document.getElementById('weakWords');if(weakBox){weakBox.innerHTML='';if(!weak.length){weakBox.innerHTML='<p class="muted">还没有足够的点击数据。学习几篇文章后，这里会自动出现需巩固词。</p>';}else weak.forEach(x=>{const item=document.createElement('div');item.className='weak-item';item.innerHTML=`<b>${x.word}</b><span>查义 ${x.meaningClicks} 次 · 复习出现 ${x.reviewSeen} 天</span>`;weakBox.append(item);});}}
function exportProgress(){const payload={exportedAt:nowISO(),progress:progressStore,mastered:[...masteredSet]};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`kaoyan-progress-${localDateKey()}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);}
function importProgress(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data?.progress?.days)throw new Error('invalid');localStorage.setItem(PROGRESS_KEY,JSON.stringify(data.progress));if(Array.isArray(data.mastered))localStorage.setItem('kaoyan_mastered',JSON.stringify(data.mastered));progressStore=data.progress;masteredSet=new Set(data.mastered||[]);renderDashboard();alert('学习进度已导入。');}catch(e){alert('无法导入：文件不是有效的考研英语学习进度备份。');}};r.readAsText(file);}
const exportBtn=document.getElementById('exportProgress');if(exportBtn)exportBtn.addEventListener('click',exportProgress);const importBtn=document.getElementById('importProgress'),importFile=document.getElementById('importProgressFile');if(importBtn&&importFile){importBtn.addEventListener('click',()=>importFile.click());importFile.addEventListener('change',()=>{const f=importFile.files?.[0];if(f)importProgress(f);importFile.value='';});}renderDashboard();
function bindTopButton(){const btn=document.getElementById('topBtn');if(!btn||btn.dataset.bound==='1')return;btn.dataset.bound='1';btn.addEventListener('click',ev=>{ev.preventDefault();try{window.scrollTo({top:0,left:0,behavior:'smooth'});}catch(e){window.scrollTo(0,0);}document.getElementById('top')?.scrollIntoView?.({block:'start'});});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindTopButton,{once:true});else bindTopButton();
})();