(()=>{
const ORIGINS={
"2026-09-16":{"imbalance":"2026-09-15","divergence":"2026-09-15","sluggish":"2026-09-15","overcapacity":"2026-09-15","bottleneck":"2026-09-15","convergence":"2026-09-15","deleverage":"2026-09-15","inequality":"2026-09-15","thrift":"2026-09-15","sentiment":"2026-09-15","appreciation":"2026-09-14","arbitrage":"2026-09-14","discretion":"2026-09-14","exacerbate":"2026-09-14","sophistication":"2026-09-14","infringement":"2026-09-13","deterrence":"2026-09-13","litigation":"2026-09-13","enforceable":"2026-09-13","authenticity":"2026-09-11"}
};
const day=(location.pathname.match(/(\d{4}-\d{2}-\d{2})\.html$/)||[])[1];
function highlightRequested(){const key=(new URLSearchParams(location.search).get('word')||'').toLowerCase();if(!key)return;let n=0;const find=()=>{const el=[...document.querySelectorAll('.article .word')].find(x=>x.dataset.word===key);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});const o=el.style.outline,oo=el.style.outlineOffset,sh=el.style.boxShadow;el.style.outline='3px solid currentColor';el.style.outlineOffset='4px';el.style.boxShadow='0 0 0 8px rgba(255,215,0,.28)';setTimeout(()=>{el.style.outline=o;el.style.outlineOffset=oo;el.style.boxShadow=sh;},2600);return;}if(++n<20)setTimeout(find,100);};setTimeout(find,100);}
function addOriginLinks(){const origins=ORIGINS[day];if(!origins)return;const details=[...document.querySelectorAll('details')].find(d=>/今日复习词/.test(d.querySelector('summary')?.textContent||''));if(!details)return;const rows=details.querySelectorAll('.vocab-item');rows.forEach(row=>{const word=(row.querySelector('.vocab-source-link')?.textContent||'').trim().toLowerCase();const first=origins[word];if(!first||row.querySelector('.review-origin-link'))return;const a=document.createElement('a');a.className='btn review-origin-link';a.textContent='📖 首学 '+first.slice(5);a.href='./'+first+'.html?word='+encodeURIComponent(word);a.style.marginLeft='8px';row.append(a);});}
function init(){highlightRequested();let n=0;const wait=()=>{addOriginLinks();if(++n<20&&!document.querySelector('.review-origin-link'))setTimeout(wait,100);};wait();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();