(()=>{
const ORIGINS={"2026-09-16":{"imbalance":"2026-09-15","divergence":"2026-09-15","sluggish":"2026-09-15","overcapacity":"2026-09-15","bottleneck":"2026-09-15","convergence":"2026-09-15","deleverage":"2026-09-15","inequality":"2026-09-15","thrift":"2026-09-15","sentiment":"2026-09-15","appreciation":"2026-09-14","arbitrage":"2026-09-14","discretion":"2026-09-14","exacerbate":"2026-09-14","sophistication":"2026-09-14","infringement":"2026-09-13","deterrence":"2026-09-13","litigation":"2026-09-13","enforceable":"2026-09-13","authenticity":"2026-09-11"}};
const MEANINGS={imbalance:'失衡',divergence:'分化；背离',sluggish:'低迷的',overcapacity:'产能过剩',bottleneck:'瓶颈',convergence:'趋同',deleverage:'去杠杆',inequality:'不平等',thrift:'节俭',sentiment:'情绪；信心',appreciation:'升值；欣赏',arbitrage:'套利',discretion:'酌情决定权',exacerbate:'加剧',sophistication:'复杂性；成熟度',infringement:'侵权',deterrence:'威慑',litigation:'诉讼',enforceable:'可执行的',authenticity:'真实性'};
const day=(location.pathname.match(/(\d{4}-\d{2}-\d{2})\.html$/)||[])[1];
const W=w=>`<span class="word" tabindex="0" data-word="${w}" data-type="review" data-meaning="${MEANINGS[w]}">${w}</span>`;
function loadSync(){if(document.querySelector('script[data-kaoyan-sync]'))return;const s=document.createElement('script');s.dataset.kaoyanSync='1';s.src='../sync.js?v=20260918-1';document.head.appendChild(s)}
function injectReviewContext(){if(day!=='2026-09-16')return;const article=document.querySelector('.article');if(!article||document.getElementById('reviewContext16'))return;const box=document.createElement('section');box.id='reviewContext16';box.className='review-context';box.innerHTML=`<div class="part"><b>🟡 Review Bridge · Connecting Yesterday to Today</b><br>把20个复习词重新放回今天“电力与工业竞争”的连续语境。</div>
<p>The energy transition can create an ${W('imbalance')} between fast-growing electricity demand and ${W('sluggish')} grid investment. That ${W('divergence')} may leave renewable projects facing ${W('overcapacity')} in generation while transmission remains the real ${W('bottleneck')}.</p>
<p>Over time, better networks can encourage ${W('convergence')} between regions, but firms still trying to ${W('deleverage')} may postpone investment. If energy costs fall unevenly, existing ${W('inequality')} can widen; household ${W('thrift')} and weak business ${W('sentiment')} can then keep demand soft even when electricity supply improves.</p>
<p>Currency ${W('appreciation')} may make imported equipment cheaper, while price gaps can invite ${W('arbitrage')}. Regulators therefore need enough ${W('discretion')} to respond to local conditions without creating uncertainty that could ${W('exacerbate')} financing risks. As power markets gain ${W('sophistication')}, transparent rules become more important.</p>
<p>Digital grids also raise governance questions. Clear rules against data or patent ${W('infringement')} can strengthen ${W('deterrence')} and reduce costly ${W('litigation')}. Contracts must be ${W('enforceable')}, while credible reporting helps investors judge the ${W('authenticity')} of corporate claims about clean electricity.</p>`;article.append(box);box.querySelectorAll('.word').forEach(el=>{el.addEventListener('click',()=>el.classList.toggle('open'));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.classList.toggle('open');}});});}
function highlightRequested(){const key=(new URLSearchParams(location.search).get('word')||'').toLowerCase();if(!key)return;let n=0;const find=()=>{const el=[...document.querySelectorAll('.article .word')].find(x=>x.dataset.word===key);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});const o=el.style.outline,oo=el.style.outlineOffset,sh=el.style.boxShadow;el.style.outline='3px solid currentColor';el.style.outlineOffset='4px';el.style.boxShadow='0 0 0 8px rgba(255,215,0,.28)';setTimeout(()=>{el.style.outline=o;el.style.outlineOffset=oo;el.style.boxShadow=sh;},2800);return;}if(++n<30)setTimeout(find,100);};setTimeout(find,100);}
function addOriginLinks(){const origins=ORIGINS[day];if(!origins)return;const details=[...document.querySelectorAll('details')].find(d=>/今日复习词/.test(d.querySelector('summary')?.textContent||''));if(!details)return;details.querySelectorAll('.vocab-item').forEach(row=>{const word=(row.querySelector('.vocab-source-link')?.textContent||'').trim().toLowerCase();const first=origins[word];if(!first||row.querySelector('.review-origin-link'))return;const here=document.createElement('button');here.type='button';here.className='btn review-here-link';here.textContent='🔎 本文语境';here.style.marginLeft='8px';here.onclick=()=>{const el=[...document.querySelectorAll('.article .word')].find(x=>x.dataset.word===word);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.style.outline='3px solid currentColor';setTimeout(()=>el.style.outline='',2200);}};const a=document.createElement('a');a.className='btn review-origin-link';a.textContent='📖 首学 '+first.slice(5);a.href='./'+first+'.html?word='+encodeURIComponent(word)+'&origin=review';a.style.marginLeft='8px';row.append(here,a);});}
function init(){loadSync();injectReviewContext();highlightRequested();let n=0;const wait=()=>{addOriginLinks();if(++n<30&&!document.querySelector('.review-origin-link'))setTimeout(wait,100);};wait();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();